import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Introduction from '../components/intro/Intoduction'
import Navbar from '../components/nav/Navbar'
import Links from '../components/links/Links'
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['main']}>
        <Introduction />
        <Links />
      </div>
      <div className={styles.container}>
        <Footer />
      </div>
    </div>
  )
}